#!/usr/bin/env sh
# Main script that does crap
set -e

# Env variables used by installation scripts.
export PATH="$PATH:$HOME/.uli/utils"

ensure_found() {
	if ! [ -d "$HOME/.uli/pkgs/$1" ]; then
		echo "Package $1 Not found." >&2
		exit 1
	fi
}

install_single() {
	ensure_found "$1"

	mkdir -p "$HOME/.uli/cache/$1"
	cd "$HOME/.uli/cache/$1"

	"$HOME/.uli/pkgs/$1/install"
	code=$?

	if [ $code = 0 ]; then
		echo "Installation for $1 finished!, no error reported."
	else
		echo "Installation for $1 failed!, error code $code"
	fi

	unset code
	unset dir
}

# installs $@
install() {
	for pkg in "$@"; do
		install_single "$pkg"
	done
}

# update local package index from github
update() {
	dir=$(mktemp -d)
	git clone --depth 1 "https://github.com/UlisseMini/uli" "$dir"
	cp -rvf "$dir/pkgs" ~/.uli/pkgs
	unset dir
}

# upgrade local packages
upgrade() {
	echo "Not implemented!"; exit 1
}

remove() {
	for pkg in "$@"; do
		remove_single "$pkg"
	done
}

remove_single() {
	ensure_found "$1"
	mkdir -p "$HOME/.uli/cache/$1"
	cd "$HOME/.uli/cache/$1"

	"$HOME/.uli/pkgs/$1/remove"
}

help() {
	cat <<EOF
	Usage: uli <command> [options...]

	install <package> [packages...] -- install a package
	update                          -- update the local package index
	upgrade                         -- upgrade/update local packages
	remove  <package> [packages...] -- remove/uninstall packages
EOF
}

cmd="$1"
shift

case "$cmd" in
	install) install $@ ;;
	isntall) install $@ ;;
	i)       install $@ ;;

	update)  update  ;;
	upgrade) upgrade ;;

	uninstall) remove $@ ;;
	remove)    remove $@ ;;
	r)         remove $@ ;;

	*) help ;;
esac
