#!/bin/bash
set -e

mkdir -p sl-src
echo Downloading sl source code from https://github.com/mtoyoda/sl/archive/5.02.tar.gz
wget -qO- https://github.com/mtoyoda/sl/archive/5.02.tar.gz | tar xz -C sl-src --strip-components=1

echo Compiling
make -s -C sl-src

echo Moving to ~/.local/bin
cp -v sl-src/sl ~/.local/bin/
