#!/usr/bin/env sh
# Download an archive, extracting at the same time as downloading.
# Args
#  $1 = URL
#  $2 = Out file name
#  $3 = Out dir name
set -e

case "$1" in
	*.tar.gz) extract="tar xz" ;;
	*.tgz)    extract="tar xz" ;;
	*.tar)    extract="tar x"  ;;
	*.zip)    extract="unzip"  ;;

	*) echo "Unknown extension for url $1"; exit 1 ;;
esac

# NOTE: Currently we do not support $3 with unzip
if [ "$extract" = unzip ]; then
	if has pv; then
		dl "$1" | pv > "$2"
		unzip -qq "$2"
	else
		dl "$1" > "$2"
		unzip -qq "$2"
	fi

	exit
fi

# I want mkdir to fail if the dir exists
mkdir "$3"

# Download it :)
if has pv; then
	dl "$1" | pv | tee "$2" | $extract -C "$3" --strip-components=1
else
	dl "$1" | tee "$2" | ${extract}v  -C "$3" --strip-components=1
fi

